{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sam.plugin",
    "module": "detector",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "detector-0.0.1.jar",
          "url": "detector-0.0.1.jar",
          "size": 1980,
          "sha512": "bb535e9efbeec45bc86acd48c913f30f0bd2891c823698749e496b85a240d25613e84a2b98ec3712e74bb07c1459330e802b136f975eb41286fcc9c6a8ecb136",
          "sha256": "5fed7c19af84f0b059e9ca2ea0e7deac773fd0fa1bbb99494d9219c744f68e54",
          "sha1": "3b5b56dcc3e5af931758ed2998913058f0997532",
          "md5": "9215a9c5df5f7395d78bb8ba2f93b449"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "detector-0.0.1.jar",
          "url": "detector-0.0.1.jar",
          "size": 1980,
          "sha512": "bb535e9efbeec45bc86acd48c913f30f0bd2891c823698749e496b85a240d25613e84a2b98ec3712e74bb07c1459330e802b136f975eb41286fcc9c6a8ecb136",
          "sha256": "5fed7c19af84f0b059e9ca2ea0e7deac773fd0fa1bbb99494d9219c744f68e54",
          "sha1": "3b5b56dcc3e5af931758ed2998913058f0997532",
          "md5": "9215a9c5df5f7395d78bb8ba2f93b449"
        }
      ]
    }
  ]
}
